### ISSUE TITLE
2 tensors

### ISSUE THREAD

**Issue by onemanlingo** [Hupperich-Manuel/LSTM-XGBoost#2]
Very good job you have done! Also good commenting. But I have run in to an issue I cant solve.
model_lstm = lstm_model(X_train_lstm, y_train_lstm, X_val_lstm, y_val_lstm, EPOCH, BATCH_SIZE, CALLBACK, plotting=True)

Epoch 1/50
172/172 [==============================] - ETA: 0s - loss: 0.0042 - mae: 0.0483

It runs one EPOCH the stops with following message.
ValueError                                Traceback (most recent call last)
<ipython-input-104-715d690f1d8d> in <module>
----> 1 model_lstm = lstm_model(X_train_lstm, y_train_lstm, X_val_lstm, y_val_lstm, EPOCH, BATCH_SIZE, CALLBACK, plotting=True)

<ipython-input-103-119881d92902> in lstm_model(X_train, y_train, X_val, y_val, EPOCH, BATCH_SIZE, CALLBACK, plotting)
     23     optimizer = tf.keras.optimizers.SGD(learning_rate=0.228, momentum =.85) #learning_rate=0.228, momentum =.85
     24     model.compile(loss=tf.keras.losses.Huber(), optimizer=optimizer, metrics="mae")
---> 25     history = model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=EPOCH, callbacks=[callbacks], validation_data=[X_val, y_val], verbose=1)
     26 
     27     if plotting == True:

ValueError: Layer sequential expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 30, 49) dtype=float32>, <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float32>]

**Comment by manuhup** [comment]
I have made some commits. You can now access the notebook on Google Colab. There it should run without problems!
